import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push('/movies');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.hero}>
        <h1 className={styles.hero__title}>
          <button onClick={handleClick} className='btn btn-warning btn-lg'>
            Movies List
          </button>
        </h1>
        <Image src='/halls.jpg' alt='halls' width={750} height={500} className={styles.img} />
      </div>
    </>
  );
}
